# Copyright © 2025 Brent Tunnicliff <brent@tunnicliff.dev>

name: 'Template action'
description: 'Replace me'
runs:
  using: "composite"
  steps:
    - name: Hello
      shell: bash
      run: echo "Hello World!"
