# Copyright © 2025 Brent Tunnicliff <brent@tunnicliff.dev>

name: 'Git Status'
description: 'Checks the git status for any local changes.'
inputs:
  fail_if_local_changes_found:
    description: 'If set as true the job will fail if any local changes are found.'
    required: false
    default: true
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Check git status
      shell: bash
      run: |
        # If no local changes, then exit successfully early.
        if [[ $(git status --porcelain) == "" ]]; then
          echo "No local changes found"
          exit 0
        fi

        echo "Local changes found"

        # Stage all changes to make sure new files will show up in the diff.
        git add .
        git diff HEAD

        if [[ ${{ inputs.fail_if_local_changes_found }} ]]; then
          exit 1
        fi
